language: cpp
os:
  - linux
compiler:
  - clang
  - gcc
addons:
  apt:
    packages: lcov
install:
  - python -m pip install --user cpplint coveralls
  - gem install coveralls-lcov
script: bash test_cpp.sh
after_success:
  - coveralls-lcov tests/cpp/coverage/coverage.info
notifications:
  webhooks: https://coveralls.io/webhook
