language: cpp
os:
  - linux
  - osx
compiler:
  - clang
  - gcc
addons:
  apt:
    packages: lcov
  homebrew:
    packages: lcov
install:
  - python -m pip install --user -r requirements.txt
  - python -m pip install --user -r requirements-dev.txt
script:  bash test_cpp.sh && bash test_py.sh
after_success:
  coveralls
notifications:
  webhooks: https://coveralls.io/webhook
