language: cpp
os:
  - linux
  - osx
compiler:
  - clang
  - gcc
cache:
  directories:
    - $HOME/Library/Caches/Homebrew
    - /usr/local/Homebrew
addons:
  apt:
    packages: lcov
install:
  - python -m pip install --user cpplint
  - if [ "${TRAVIS_OS_NAME}" = "osx" ]; then brew update && brew install lcov; fi
script:  bash test_cpp.sh
after_success:
  coveralls
notifications:
  webhooks: https://coveralls.io/webhook
