MIXAL: mixal::IODeviceStorage Class Reference
mixal::IODeviceStorage Class Reference
#include <io.h>
Public Member Functions
IODeviceStorage (int32_t storageSize=4096)
IODeviceStorage (const IODeviceStorage &)=default
IODeviceStorage & operator= (const IODeviceStorage &)=default
bool ready (int32_t elapsed) override
void read (ComputerWord *memory, int32_t address) override
void write (const ComputerWord *memory, int32_t address) override
ComputerWord & wordAt (int32_t index) override
Public Member Functions inherited from mixal::IODevice
IODevice (int32_t blockSize, bool allowRead, bool allowWrite)
IODeviceType type () const
int blockSize () const
bool allowRead () const
bool allowWrite () const
virtual void control (int32_t)
Protected Member Functions
void doRead () override
void doWrite () override
Protected Attributes
IODeviceStatus _status
int32_t _address
int32_t _locator
ComputerWord * _memory
std::vector< ComputerWord > _buffer
std::vector< ComputerWord > _storage
Protected Attributes inherited from mixal::IODevice
IODeviceType _type
int32_t _blockSize
bool _allowRead
bool _allowWrite
int32_t _timestamp
double _readyRate
Detailed Description
Device with a storage.
Definition at line 87 of file io.h.
Member Function Documentation
doRead()
void mixal::IODeviceStorage::doRead () override protected virtual
Perform the actual reading.
Implements mixal::IODevice.
Definition at line 56 of file io.cpp.
{
     for (int i = 0; i < _blockSize; ++i) {
         _memory[_address + i] = _buffer[i];
     }
     _status = IODeviceStatus::READY;
 }
References mixal::IODevice::_blockSize.
Referenced by ready().
doWrite()
void mixal::IODeviceStorage::doWrite () override protected virtual
Perform the actual writing.
Implements mixal::IODevice.
Definition at line 63 of file io.cpp.
{
     for (int i = 0; i < _blockSize; ++i) {
         _storage[_locator + i] = _buffer[i];
     }
     _status = IODeviceStatus::READY;
 }
References mixal::IODevice::_blockSize.
read()
void mixal::IODeviceStorage::read (ComputerWord * memory, int32_t address) override virtual
Read one block from the device.
Implements mixal::IODevice.
Definition at line 38 of file io.cpp.
{
     _status = IODeviceStatus::BUSY_READ;
     _address = address;
     _memory = memory;
     for (int i = 0; i < _blockSize; ++i) {
         _buffer[i] = _storage[_locator + i];
     }
     ready(_timestamp);
 }
References mixal::IODevice::_blockSize, mixal::IODevice::_timestamp, and ready().
ready()
bool mixal::IODeviceStorage::ready (int32_t elapsed) override virtual
Whether the device is ready for reading or writing.
Reimplemented from mixal::IODevice.
Definition at line 26 of file io.cpp.
{
     bool state = IODevice::ready(elapsed);
     if (state) {
         if (_status == IODeviceStatus::BUSY_READ) {
             doRead();
         } else if (_status == IODeviceStatus::BUSY_WRITE) {
             doWrite();
         }
     }
     return state;
 }
References doRead(), and mixal::IODevice::ready().
Referenced by read().
wordAt()
ComputerWord& mixal::IODeviceStorage::wordAt (int32_t index) inline override virtual
Get a word from the storage of the device.
Implements mixal::IODevice.
Definition at line 97 of file io.h.
 { return _storage[index]; }
write()
void mixal::IODeviceStorage::write (const ComputerWord * memory, int32_t address) override virtual
Write one block to the device.
Implements mixal::IODevice.
Definition at line 48 of file io.cpp.
{
     _status = IODeviceStatus::BUSY_WRITE;
     for (int i = 0; i < _blockSize; ++i) {
         _buffer[i] = memory[address + i];
     }
     ready(_timestamp);
 }
The documentation for this class was generated from the following files:
include/io.h
src/io.cpp