MIXAL: mixal::Computer Class Reference
mixal::Computer Class Reference
Public Member Functions
Computer ()
Register2 & rI (int index)
const ComputerWord & memoryAt (int16_t index) const
ComputerWord & memoryAt (int16_t index)
IODevice * getDevice (int32_t index)
void waitDevice (IODevice *device)
void waitDevices ()
ComputerWord & getDeviceWordAt (int32_t device, int32_t index)
void reset ()
int line () const
int elapsed () const
std::string getSingleLineSymbol ()
void executeSingle ()
void executeUntilSelfLoop ()
void executeUntilHalt ()
void executeSingle (ParsedResult *instruction)
void executeSingle (const InstructionWord &instruction)
void executeSinglePesudo (ParsedResult *instruction)
void loadCodes (const std::string &codes, bool addHalt=true)
void loadCodes (const std::vector< std::string > &codes, bool addHalt=true)
Public Attributes
Register5 rA
Register5 rX
Register2 rI1
Register2 rI2
Register2 rI3
Register2 rI4
Register2 rI5
Register2 rI6
Register2 rJ
bool overflow
ComparisonIndicator comparison
ComputerWord memory [NUM_MEMORY]
std::vector< IODevice * > devices
Static Public Attributes
static const int NUM_INDEX_REGISTER = 6
static const int NUM_MEMORY = 4000
static const int NUM_IO_DEVICE = 21
Detailed Description
Definition at line 26 of file machine.h.
Constructor & Destructor Documentation
Computer()
mixal::Computer::Computer ()
Initialize the machine with zeros.
Definition at line 11 of file machine.cpp.
                    : rA(), rX(), rI1(), rI2(), rI3(), rI4(), rI5(), rI6(), rJ(),
       overflow(false), comparison(ComparisonIndicator::EQUAL), memory(),
       devices(NUM_IO_DEVICE, nullptr),
       _pesudoVarIndex(), _lineOffset(), _elapsed(), _constants() {}
Member Function Documentation
elapsed()
int mixal::Computer::elapsed () const inline
Get elapsed unit time after executing the codes.
Definition at line 65 of file machine.h.
 { return _elapsed; }
executeSingle() [1/3]
void mixal::Computer::executeSingle ()
Execute a single instruction in the memory.
Definition at line 69 of file machine.cpp.
{
     executeSingle(memory[_lineOffset]);
 }
References executeSingle(), and memory.
Referenced by executeSingle(), executeUntilHalt(), and executeUntilSelfLoop().
executeSingle() [2/3]
void mixal::Computer::executeSingle (const InstructionWord & instruction)
Execute a single instruction based on the given instruction.
Definition at line 121 of file machine.cpp.
{
     switch (instruction.operation()) {
     case Instructions::ADD:
         executeADD(instruction);
         break;
     case Instructions::SUB:
         executeSUB(instruction);
         break;
     case Instructions::MUL:
         executeMUL(instruction);
         break;
     case Instructions::DIV:
         executeDIV(instruction);
         break;
     case Instructions::HLT:
         switch (instruction.field()) {
         case 0: executeNUM(); break;
         case 1: executeCHAR(); break;
         }
         break;
     case Instructions::SLA:
         switch (instruction.field()) {
         case 0: executeSLA(instruction); break;
         case 1: executeSRA(instruction); break;
         case 2: executeSLAX(instruction); break;
         case 3: executeSRAX(instruction); break;
         case 4: executeSLC(instruction); break;
         case 5: executeSRC(instruction); break;
         }
         break;
     case Instructions::MOVE:
         executeMOVE(instruction);
         break;
     case Instructions::LDA:
         executeLD(instruction, &rA);
         break;
     case Instructions::LD1:
     case Instructions::LD2:
     case Instructions::LD3:
     case Instructions::LD4:
     case Instructions::LD5:
     case Instructions::LD6:
         executeLDi(instruction);
         break;
     case Instructions::LDX:
         executeLD(instruction, &rX);
         break;
     case Instructions::LDAN:
         executeLDN(instruction, &rA);
         break;
     case Instructions::LD1N:
     case Instructions::LD2N:
     case Instructions::LD3N:
     case Instructions::LD4N:
     case Instructions::LD5N:
     case Instructions::LD6N:
         executeLDiN(instruction);
         break;
     case Instructions::LDXN:
         executeLDN(instruction, &rX);
         break;
     case Instructions::STA:
         executeST(instruction, &rA);
         break;
     case Instructions::ST1:
     case Instructions::ST2:
     case Instructions::ST3:
     case Instructions::ST4:
     case Instructions::ST5:
     case Instructions::ST6:
         executeSTi(instruction);
         break;
     case Instructions::STX:
         executeST(instruction, &rX);
         break;
     case Instructions::STJ:
         executeSTJ(instruction);
         break;
     case Instructions::STZ:
         executeSTZ(instruction);
         break;
     case Instructions::JBUS:
         executeJBUS(instruction);
         break;
     case Instructions::IOC:
         executeIOC(instruction);
         break;
     case Instructions::IN:
         executeIN(instruction);
         break;
     case Instructions::OUT:
         executeOUT(instruction);
         break;
     case Instructions::JRED:
         executeJRED(instruction);
         break;
     case Instructions::JMP:
         switch (instruction.field()) {
         case 0: executeJMP(instruction); break;
         case 1: executeJSJ(instruction); break;
         case 2: executeJOV(instruction); break;
         case 3: executeJNOV(instruction); break;
         case 4: executeJL(instruction); break;
         case 5: executeJE(instruction); break;
         case 6: executeJG(instruction); break;
         case 7: executeJGE(instruction); break;
         case 8: executeJNE(instruction); break;
         case 9: executeJLE(instruction); break;
         }
         break;
     case Instructions::JAN:
         switch (instruction.field()) {
         case 0: executeJN(instruction, &rA); break;
         case 1: executeJZ(instruction, &rA); break;
         case 2: executeJP(instruction, &rA); break;
         case 3: executeJNN(instruction, &rA); break;
         case 4: executeJNZ(instruction, &rA); break;
         case 5: executeJNP(instruction, &rA); break;
         }
         break;
     case Instructions::J1N:
     case Instructions::J2N:
     case Instructions::J3N:
     case Instructions::J4N:
     case Instructions::J5N:
     case Instructions::J6N:
         switch (instruction.field()) {
         case 0: executeJiN(instruction); break;
         case 1: executeJiZ(instruction); break;
         case 2: executeJiP(instruction); break;
         case 3: executeJiNN(instruction); break;
         case 4: executeJiNZ(instruction); break;
         case 5: executeJiNP(instruction); break;
         }
         break;
     case Instructions::JXN:
         switch (instruction.field()) {
         case 0: executeJN(instruction, &rX); break;
         case 1: executeJZ(instruction, &rX); break;
         case 2: executeJP(instruction, &rX); break;
         case 3: executeJNN(instruction, &rX); break;
         case 4: executeJNZ(instruction, &rX); break;
         case 5: executeJNP(instruction, &rX); break;
         }
         break;
     case Instructions::INCA:
         switch (instruction.field()) {
         case 0: executeINC(instruction, &rA); break;
         case 1: executeDEC(instruction, &rA); break;
         case 2: executeENT(instruction, &rA); break;
         case 3: executeENN(instruction, &rA); break;
         }
         break;
     case Instructions::INC1:
     case Instructions::INC2:
     case Instructions::INC3:
     case Instructions::INC4:
     case Instructions::INC5:
     case Instructions::INC6:
         switch (instruction.field()) {
         case 0: executeINCi(instruction); break;
         case 1: executeDECi(instruction); break;
         case 2: executeENTi(instruction); break;
         case 3: executeENNi(instruction); break;
         }
         break;
     case Instructions::INCX:
         switch (instruction.field()) {
         case 0: executeINC(instruction, &rX); break;
         case 1: executeDEC(instruction, &rX); break;
         case 2: executeENT(instruction, &rX); break;
         case 3: executeENN(instruction, &rX); break;
         }
         break;
     case Instructions::CMPA:
         executeCMP(instruction, &rA);
         break;
     case Instructions::CMP1:
     case Instructions::CMP2:
     case Instructions::CMP3:
     case Instructions::CMP4:
     case Instructions::CMP5:
     case Instructions::CMP6:
         executeCMPi(instruction);
         break;
     case Instructions::CMPX:
         executeCMP(instruction, &rX);
         break;
     }
     ++_lineOffset;
     _elapsed += Instructions::getCost(static_cast<Instructions::Code>(instruction.operation()),
                                       instruction.field());
 }
References mixal::ComputerWord::field(), mixal::Instructions::getCost(), mixal::ComputerWord::operation(), rA, and rX.
executeSingle() [3/3]
void mixal::Computer::executeSingle (ParsedResult * instruction)
Execute a single instruction based on the given instruction.
Definition at line 103 of file machine.cpp.
{
     if (instruction->address.literalConstant() ||
         instruction->index.literalConstant() ||
         instruction->field.literalConstant()) {
         throw RuntimeError(_lineOffset, "Literal constant cannot be used in single execution");
     }
     if (instruction->parsedType == ParsedType::INSTRUCTION) {
         if (!instruction->evaluated()) {
             if (!instruction->evaluate(_constants)) {
                 throw RuntimeError(_lineOffset, "Unresolved symbol found when trying to execute");
             }
         }
         executeSingle(instruction->word);
     } else if (instruction->parsedType == ParsedType::PSEUDO) {
         executeSinglePesudo(instruction);
     }
 }
References mixal::ParsedResult::address, mixal::ParsedResult::evaluate(), mixal::ParsedResult::evaluated(), executeSingle(), executeSinglePesudo(), mixal::ParsedResult::field, mixal::ParsedResult::index, mixal::Expression::literalConstant(), mixal::ParsedResult::parsedType, and mixal::ParsedResult::word.
executeSinglePesudo()
void mixal::Computer::executeSinglePesudo (ParsedResult * instruction)
Execute a single pesudo instruction.
Definition at line 315 of file machine.cpp.
{
     switch (instruction->word.operation() + Instructions::PSEUDO) {
     case Instructions::EQU:
         executeEQU(instruction);
         break;
     case Instructions::ORIG:
         executeORIG(instruction);
         break;
     case Instructions::CON:
         executeCON(instruction);
         break;
     }
 }
References mixal::ComputerWord::operation(), and mixal::ParsedResult::word.
Referenced by executeSingle().
executeUntilHalt()
void mixal::Computer::executeUntilHalt ()
Execute instructions until the HLT operation has been met.
Definition at line 88 of file machine.cpp.
{
     while (true) {
         if (_lineOffset < 0 || NUM_MEMORY <= _lineOffset) {
             throw RuntimeError(_lineOffset, "Invalid code line: " + std::to_string(_lineOffset));
         }
         if (memory[_lineOffset].operation() == Instructions::HLT &&
             memory[_lineOffset].field() == 2) {
             ++_lineOffset;
             break;
         }
         executeSingle(memory[_lineOffset]);
     }
     waitDevices();
 }
References executeSingle(), memory, NUM_MEMORY, and waitDevices().
executeUntilSelfLoop()
void mixal::Computer::executeUntilSelfLoop ()
Execute instructions until there is a self loop.
Definition at line 73 of file machine.cpp.
{
     int32_t lastOffset = _lineOffset;
     while (true) {
         if (_lineOffset < 0 || NUM_MEMORY <= _lineOffset) {
             throw RuntimeError(_lineOffset, "Invalid code line: " + std::to_string(_lineOffset));
         }
         executeSingle(memory[_lineOffset]);
         if (lastOffset == _lineOffset) {
             break;
         }
         lastOffset = _lineOffset;
     }
     waitDevices();
 }
References executeSingle(), memory, NUM_MEMORY, and waitDevices().
getDevice()
IODevice * mixal::Computer::getDevice (int32_t index)
Get the device based on the index value.
Definition at line 11 of file machine_io.cpp.
{
     if (devices[index] == nullptr) {
         switch (index) {
         case 0: case 1: case 2: case 3:
         case 4: case 5: case 6: case 7:
             devices[index] = new IODeviceTape();
             break;
         case 8: case 9: case 10: case 11:
         case 12: case 13: case 14: case 15:
             devices[index] = new IODeviceDisk();
             break;
         case 16:
             devices[index] = new IODeviceCardReader();
             break;
         case 17:
             devices[index] = new IODeviceCardPunch();
             break;
         case 18:
             devices[index] = new IODeviceLinePrinter();
             break;
         case 19:
             devices[index] = new IODeviceTypewriter();
             break;
         case 20:
             devices[index] = new IODevicePaperTape();
             break;
         }
     }
     return devices[index];
 }
References devices.
Referenced by getDeviceWordAt().
getDeviceWordAt()
ComputerWord & mixal::Computer::getDeviceWordAt (int32_t device, int32_t index)
Get a word from a device.
Definition at line 56 of file machine_io.cpp.
{
     return this->getDevice(device)->wordAt(index);
 }
References getDevice(), and mixal::IODevice::wordAt().
getSingleLineSymbol()
std::string mixal::Computer::getSingleLineSymbol ()
Get a unique symbol name.
Definition at line 63 of file machine.cpp.
{
     std::string symbolName = getPesudoSymbolname();
     _constants[symbolName] = AtomicValue(_lineOffset);
     return symbolName;
 }
line()
int mixal::Computer::line () const inline
Get the current executing line of the memory.
Definition at line 63 of file machine.h.
 { return _lineOffset; }
loadCodes() [1/2]
void mixal::Computer::loadCodes (const std::string & codes, bool addHalt = true)
Parse and load codes to memory.
Definition at line 329 of file machine.cpp.
{
     std::vector<std::string> lines;
     std::string item;
     std::stringstream ss(codes);
     while (std::getline(ss, item, '\n')) {
         lines.emplace_back(item);
     }
     loadCodes(lines, addHalt);
 }
loadCodes() [2/2]
void mixal::Computer::loadCodes (const std::vector< std::string > & codes, bool addHalt = true)
Parse and load codes to memory.
Definition at line 339 of file machine.cpp.
{
     // Parse and save all the results and intermediate expressions
     std::vector<ParsedResult> results(codes.size());
     std::unordered_map<std::string, AtomicValue> evaluated;
     std::unordered_map<std::string, Expression*> expressions;
     std::vector<std::tuple<std::string, Expression, Expression>> constants;  // (name, address, value)
     std::string lineBase = getPesudoSymbolname();
     evaluated[lineBase] = AtomicValue(0);
     int32_t lineOffset = 0, endIndex = -1;
     for (size_t codeIndex = 0; codeIndex < codes.size(); ++codeIndex) {
         auto code = codes[codeIndex];
         auto& result = results[codeIndex];
         auto lineSymbol = getPesudoSymbolname();
         result = Parser::parseLine(code, lineSymbol, true);
         if (result.parsedType == ParsedType::PSEUDO) {
             int32_t operation = result.word.operation() + Instructions::PSEUDO;
             switch (operation) {
             case Instructions::EQU:
                 expressions[result.rawLocation] = &result.address;
                 break;
             case Instructions::ORIG:
                 if (result.rawAddress.find('*') == std::string::npos) {
                     if (!result.rawLocation.empty()) {
                         expressions[result.rawLocation] = &result.address;
                     }
                 } else {
                      // When there is a `*` in the address, the location should equal to
                      // the `*` value before the calculation.
                     result.location = Expression::getConstOffsetExpression(lineBase, lineOffset);
                     expressions[result.rawLocation] = &result.location;
                     expressions[lineSymbol] = &result.location;
                 }
                 lineBase = getPesudoSymbolname();
                 expressions[lineBase] = &result.address;
                 lineOffset = 0;
                 break;
             case Instructions::CON:
             case Instructions::ALF:
                 if (!result.rawLocation.empty()) {
                     lineSymbol = result.rawLocation;
                 }
                 constants.push_back(std::make_tuple(
                     lineSymbol,
                     Expression::getConstOffsetExpression(lineBase, lineOffset++),
                     result.address));
                 break;
             case Instructions::END:
                 endIndex = codeIndex;
                 break;
             }
         } else if (result.parsedType == ParsedType::INSTRUCTION) {
             bool usedLineSymbol = !result.rawLocation.empty() ||
                                 (!result.rawAddress.empty() && result.address.depends().count(lineSymbol)) ||
                                 (!result.rawIndex.empty() && result.index.depends().count(lineSymbol)) ||
                                 (!result.rawField.empty() && result.field.depends().count(lineSymbol));
             result.location = Expression::getConstOffsetExpression(lineBase, lineOffset);
             if (!result.rawLocation.empty()) {
                 if (!(Atomic::isLocalSymbol(result.rawLocation) && result.rawLocation[1] == 'H')) {
                     expressions[result.rawLocation] = &result.location;
                 }
             } else if (usedLineSymbol) {
                 result.rawLocation = lineSymbol;
             }
             expressions[lineSymbol] = &result.location;
             ++lineOffset;
         }
     }
     // Replace local symbols
     std::unordered_map<std::string, std::string> localSymbolMapping;
     for (auto& result : results) {
         if (!result.rawLocation.empty() && Atomic::isLocalSymbol(result.rawLocation) && result.rawLocation[1] == 'H') {
             auto lineSymbol = getPesudoSymbolname();
             result.rawLocation[1] = 'B';
             localSymbolMapping[result.rawLocation] = lineSymbol;
             result.rawLocation[1] = 'H';
             expressions[lineSymbol] = &result.location;
         }
         result.address.replaceSymbol(localSymbolMapping);
     }
     for (int i = static_cast<int>(results.size()) - 1; i >= 0; --i) {
         auto& result = results[i];
         if (!result.rawLocation.empty() && Atomic::isLocalSymbol(result.rawLocation) && result.rawLocation[1] == 'H') {
             auto lineSymbol = getPesudoSymbolname();
             result.rawLocation[1] = 'F';
             localSymbolMapping[result.rawLocation] = lineSymbol;
             result.rawLocation[1] = 'H';
             expressions[lineSymbol] = &result.location;
         }
         result.address.replaceSymbol(localSymbolMapping);
     }
     // Add halt
     if (addHalt) {
         auto lineSymbol = getPesudoSymbolname();
         auto haltCommand = Parser::parseLine("HLT", lineSymbol, false);
         constants.push_back(std::make_tuple(
             lineSymbol,
              Expression::getConstOffsetExpression(lineBase, lineOffset++),
              Expression::getConstExpression(AtomicValue(haltCommand.word.value()))));
     }
     // Add expressions and literal constants
     for (auto& result : results) {
         if (!result.rawAddress.empty()) {
             if (result.address.literalConstant()) {
                 auto lineSymbol = getPesudoSymbolname();
                 constants.push_back(std::make_tuple(
                     lineSymbol,
                     Expression::getConstOffsetExpression(lineBase, lineOffset++),
                     result.address));
                 result.address = Expression::getConstExpression(lineSymbol);
             }
             expressions[getPesudoSymbolname()] = &result.address;
         }
         if (!result.rawIndex.empty()) {
             expressions[getPesudoSymbolname()] = &result.index;
         }
         if (!result.rawField.empty()) {
             expressions[getPesudoSymbolname()] = &result.field;
         }
     }
     if (endIndex != -1) {
         auto lineSymbol = results[endIndex].rawLocation.empty() ? getPesudoSymbolname() : results[endIndex].rawLocation;
         constants.push_back(std::make_tuple(
             lineSymbol,
             Expression::getConstOffsetExpression(lineBase, lineOffset++),
             results[endIndex].address));
     }
     // Add collected constants to expressions
     for (auto& it : constants) {
         expressions[std::get<0>(it)] = &std::get<1>(it);
         expressions[getPesudoSymbolname()] = &std::get<2>(it);
     }
     // Try to solve all the expressions
     std::unordered_map<std::string, int> dependNums;
     std::unordered_map<std::string, std::unordered_set<std::string>> solves;
     std::set<std::pair<int, std::string>> tasks;
     for (auto& it : expressions) {
         dependNums[it.first] = static_cast<int>(it.second->depends().size());
         for (auto& depend : it.second->depends()) {
             solves[depend].insert(it.first);
             if (evaluated.find(depend) != evaluated.end()) {
                 --dependNums[it.first];
             }
         }
         tasks.insert({dependNums[it.first], it.first});
     }
     while (!tasks.empty()) {
         auto& symbol = tasks.begin()->second;
         auto& expression = expressions[symbol];
         if (tasks.begin()->first != 0 || !expression->evaluate(evaluated)) {
             std::ostringstream oss;
             oss << "Unresolved symbol found while trying to calcuate: ";
             oss << tasks.begin()->second << "=" << *expression;
             throw RuntimeError(0, oss.str());
         }
         evaluated[symbol] = expression->result();
         tasks.erase({0, symbol});
         for (auto& solve : solves[symbol]) {
             tasks.erase({dependNums[solve], solve});
             tasks.insert({--dependNums[solve], solve});
         }
     }
     // Load constants to memory
     for (auto& it : constants) {
         int32_t location = std::get<1>(it).result().value;
         if (location < 0 || location >= NUM_MEMORY) {
             throw RuntimeError(location, "Location of the code is invalid: " + std::to_string(location));
         }
         memory[location].set(std::get<2>(it).result().value);
     }
     // Load results to memory
     _lineOffset = -1;
     for (auto& result : results) {
         if (result.parsedType == ParsedType::INSTRUCTION) {
             result.evaluate(evaluated);
             int32_t location = result.location.result().value;
             if (location < 0 || location >= NUM_MEMORY) {
                 throw RuntimeError(location, "Location of the code is invalid: " + std::to_string(location));
             }
             if (_lineOffset == -1) {
                 _lineOffset = location;
             }
             memory[location].set(result.word.negative,
                                  result.word.address(),
                                  result.word.index(),
                                  result.word.field(),
                                  result.word.operation());
         }
     }
     if (endIndex != -1) {
         results[endIndex].address.evaluate(evaluated);
         _lineOffset = results[endIndex].address.result().value;
     } else if (_lineOffset == -1) {
         _lineOffset = 0;
     }
 }
References mixal::Expression::getConstExpression(), mixal::Expression::getConstOffsetExpression(), mixal::Atomic::isLocalSymbol(), memory, NUM_MEMORY, mixal::Parser::parseLine(), and mixal::ComputerWord::set().
memoryAt() [1/2]
ComputerWord & mixal::Computer::memoryAt (int16_t index)
Get a word from the memory.
Definition at line 38 of file machine.cpp.
{
     return memory[index];
 }
References memory.
memoryAt() [2/2]
const ComputerWord & mixal::Computer::memoryAt (int16_t index) const
Get a word from the memory.
Definition at line 34 of file machine.cpp.
{
     return memory[index];
 }
References memory.
reset()
void mixal::Computer::reset ()
Reset the machine to zeros.
Definition at line 42 of file machine.cpp.
                      {
     rA.reset();
     rX.reset();
     for (int i = 1; i <= NUM_INDEX_REGISTER; ++i) {
         rI(i).reset();
     }
     rJ.reset();
     overflow = false;
     comparison = ComparisonIndicator::EQUAL;
     for (int i = 0; i < NUM_MEMORY; ++i) {
         memory[i].reset();
     }
     for (size_t i = 0; i < NUM_IO_DEVICE; ++i) {
         devices[i] = nullptr;
     }
     _pesudoVarIndex = 0;
     _lineOffset = 0;
     _elapsed = 0;
     _constants.clear();
 }
References comparison, devices, memory, NUM_INDEX_REGISTER, NUM_IO_DEVICE, NUM_MEMORY, overflow, rA, mixal::ComputerWord::reset(), mixal::Register2::reset(), rI(), rJ, and rX.
rI()
Register2 & mixal::Computer::rI (int index)
Get the index register given the index of the register.
Definition at line 16 of file machine.cpp.
{
     switch (index) {
     case 1: return rI1;
     case 2: return rI2;
     case 3: return rI3;
     case 4: return rI4;
     case 5: return rI5;
     case 6: return rI6;
     }
     throw RuntimeError(_lineOffset, "Invalid offset for index register: " + std::to_string(index));
 }
References rI1.
Referenced by reset().
waitDevice()
void mixal::Computer::waitDevice (IODevice * device)
Wait the IO device to be ready.
Definition at line 42 of file machine_io.cpp.
{
     while (!device->ready(this->_elapsed)) {
         ++this->_elapsed;
     }
 }
References mixal::IODevice::ready().
Referenced by waitDevices().
waitDevices()
void mixal::Computer::waitDevices ()
Wait all IO devices to be ready.
Definition at line 48 of file machine_io.cpp.
{
     for (int i = 0; i < NUM_IO_DEVICE; ++i) {
         if (devices[i] != nullptr) {
             waitDevice(devices[i]);
         }
     }
 }
References devices, NUM_IO_DEVICE, and waitDevice().
Referenced by executeUntilHalt(), and executeUntilSelfLoop().
Member Data Documentation
comparison
ComparisonIndicator mixal::Computer::comparison
The result of comparison operations.
Definition at line 36 of file machine.h.
Referenced by reset().
devices
std::vector<IODevice*> mixal::Computer::devices
The IO devices.
Definition at line 39 of file machine.h.
Referenced by getDevice(), reset(), and waitDevices().
memory
ComputerWord mixal::Computer::memory[NUM_MEMORY]
The memory in the machine.
Definition at line 38 of file machine.h.
Referenced by executeSingle(), executeUntilHalt(), executeUntilSelfLoop(), loadCodes(), memoryAt(), and reset().
NUM_INDEX_REGISTER
const int mixal::Computer::NUM_INDEX_REGISTER = 6 static
Number of index registers.
Definition at line 28 of file machine.h.
Referenced by reset().
NUM_IO_DEVICE
const int mixal::Computer::NUM_IO_DEVICE = 21 static
Number of IO devices.
Definition at line 30 of file machine.h.
Referenced by reset(), and waitDevices().
NUM_MEMORY
const int mixal::Computer::NUM_MEMORY = 4000 static
Number of words in memory.
Definition at line 29 of file machine.h.
Referenced by executeUntilHalt(), executeUntilSelfLoop(), loadCodes(), and reset().
overflow
bool mixal::Computer::overflow
Whether overflow has been triggered.
Definition at line 35 of file machine.h.
Referenced by reset().
rA
Register5 mixal::Computer::rA
Accumulator register.
Definition at line 32 of file machine.h.
Referenced by executeSingle(), and reset().
rI1
Register2 mixal::Computer::rI1
< Index register.
Definition at line 33 of file machine.h.
Referenced by rI().
rJ
Register2 mixal::Computer::rJ
Jump address register.
Definition at line 33 of file machine.h.
Referenced by reset().
rX
Register5 mixal::Computer::rX
Extension register.
Definition at line 32 of file machine.h.
Referenced by executeSingle(), and reset().
The documentation for this class was generated from the following files:
include/machine.h
src/machine.cpp
src/machine_address_transfer.cpp
src/machine_arithmetic.cpp
src/machine_comparison.cpp
src/machine_conversion.cpp
src/machine_io.cpp
src/machine_jump.cpp
src/machine_load.cpp
src/machine_misc.cpp
src/machine_pesudo.cpp
src/machine_store.cpp