MIXAL: src/expression.cpp File Reference
expression.cpp File Reference
The parsing and evaluation of expressions.
#include <cassert>
#include <limits>
#include <iostream>
#include "expression.h"
Enumerations
enum mixal::ExprParseState { mixal::ExprParseState::START, mixal::ExprParseState::ATOMIC, mixal::ExprParseState::OPERATION, mixal::ExprParseState::END }
Functions
bool mixal::isOperationFirst (char ch)
std::ostream & mixal::operator<< (std::ostream &out, Operation operation)
std::ostream & mixal::operator<< (std::ostream &out, const Expression &expression)
Detailed Description
The parsing and evaluation of expressions.
Definition in file expression.cpp.
Enumeration Type Documentation
ExprParseState
enum mixal::ExprParseState strong
The states while parsing the expression.
EXPRESSION -> + EXPRESSION
            | - EXPRESSION
            | EXPRESSION OPERATOR EXPRESSION
            | ATOMIC
OPERATOR -> + | - | * | / | // | :
ATOMIC -> INTEGER
        | SYMBOL
        | *
INTEGER -> DIGIT
         | DIGIT INTEGER
SYMBOL -> ALPHA
        | DIGIT
        | ALPHS SYMBOL
        | DIGIT SYMBOL
DIGIT -> [0-9]
ALPHA -> [A-Z]
However, multiple signs like ++ or --- will be rejected as they are useless.
Definition at line 77 of file expression.cpp.
{
     START,
     ATOMIC,
     OPERATION,
     END,
 };
Function Documentation
isOperationFirst()
bool mixal::isOperationFirst (char ch) inline
Whether an operation can start with the given character.
Definition at line 85 of file expression.cpp.
{
     return ch == '+' || ch == '-' || ch == '*' || ch == '/' || ch == ':';
 }
References mixal::isOperationFirst().
Referenced by mixal::isOperationFirst(), and mixal::Expression::parse().
operator<<() [1/2]
std::ostream& mixal::operator<< (std::ostream & out, const Expression & expression)
Output the expression.
Definition at line 346 of file expression.cpp.
{
     if (expression._atomics.size() > 0) {
         out << expression._atomics[0];
     }
     for (size_t i = 0; i < expression._operations.size(); ++i) {
         out << expression._operations[i];
         out << expression._atomics[i + 1];
     }
     return out;
 }
References mixal::operator<<().
operator<<() [2/2]
std::ostream & mixal::operator<< (std::ostream & out, Operation operation)
Output the symbol of the operation.
Definition at line 335 of file expression.cpp.
{
     switch (operation) {
     case Operation::ADD: out << '+'; break;
     case Operation::SUBTRACT: out << '-'; break;
     case Operation::MULTIPLY: out << '*'; break;
     case Operation::FLOOR_DIV: out << '/'; break;
     case Operation::FIELD: out << ':'; break;
     }
     return out;
 }
References mixal::operator<<().
Referenced by mixal::operator<<().