MIXAL: src/parser.cpp File Reference
parser.cpp File Reference
The parsing of one line of code.
#include <cassert>
#include <iostream>
#include "parser.h"
#include "instructions.h"
Enumerations
enum mixal::ParseState {
mixal::ParseState::START, mixal::ParseState::LOC, mixal::ParseState::BEFORE_OP, mixal::ParseState::OP,
mixal::ParseState::BEFORE_ADDRESS, mixal::ParseState::ADDRESS, mixal::ParseState::BEFORE_INDEX, mixal::ParseState::INDEX,
mixal::ParseState::FIELD_OPEN, mixal::ParseState::FIELD, mixal::ParseState::FIELD_CLOSE, mixal::ParseState::BEFORE_COMMENT,
mixal::ParseState::COMMENT, mixal::ParseState::END
}
Functions
std::ostream & mixal::operator<< (std::ostream &os, ParsedType c)
std::ostream & mixal::operator<< (std::ostream &out, const ParsedResult &result)
Detailed Description
The parsing of one line of code.
Definition in file parser.cpp.
Enumeration Type Documentation
ParseState
enum mixal::ParseState strong
The state while parsing a line.
LOC OP ADDRESS,INDEX(FIELD) COMMENT
Definition at line 19 of file parser.cpp.
                       {
     START,
     LOC,
     BEFORE_OP,
     OP,
     BEFORE_ADDRESS,
     ADDRESS,
     BEFORE_INDEX,
     INDEX,
     FIELD_OPEN,
     FIELD,
     FIELD_CLOSE,
     BEFORE_COMMENT,
     COMMENT,
     END,
 };
Function Documentation
operator<<() [1/2]
std::ostream & mixal::operator<< (std::ostream & os, ParsedType c)
Output the name of a parsed type.
Definition at line 36 of file parser.cpp.
{
     switch (c) {
     case ParsedType::EMPTY: os << "EMPTY"; break;
     case ParsedType::INSTRUCTION: os << "INSTRUCTION"; break;
     case ParsedType::PSEUDO: os << "PSEUDO"; break;
     }
     return os;
 }
References mixal::operator<<().
operator<<() [2/2]
std::ostream& mixal::operator<< (std::ostream & out, const ParsedResult & result)
Output the instruction.
Definition at line 112 of file parser.cpp.
{
     if (result.location.evaluated()) {
         out << result.location.result().value << '\t';
     } else {
         out << result.rawLocation << '\t';
     }
     out << result.operation << '\t';
     if (!result.rawAddress.empty()) {
         if (result.address.evaluated()) {
             out << result.address.result().value;
         } else {
             out << result.address;
         }
     }
     if (!result.rawIndex.empty()) {
         if (result.index.evaluated()) {
             out << ',' << result.index.result().value;
         } else {
             out << ',' << result.index;
         }
     }
     if (!result.rawField.empty()) {
         if (result.field.evaluated()) {
             out << '(' << result.field.result().value << ')';
         } else {
             out << '(' << result.field << ')';
         }
     }
     return out;
 }
References mixal::ParsedResult::address, mixal::Expression::evaluated(), mixal::ParsedResult::field, mixal::ParsedResult::index, mixal::ParsedResult::location, mixal::ParsedResult::operation, mixal::operator<<(), mixal::ParsedResult::rawAddress, mixal::ParsedResult::rawField, mixal::ParsedResult::rawIndex, mixal::ParsedResult::rawLocation, and mixal::Expression::result().