MIXAL: mixal::Register2 Struct Reference
mixal::Register2 Struct Reference
#include <registers.h>
Public Member Functions
Register2 ()
Register2 (int16_t value)
Register2 (bool _negative, uint8_t _byte1, uint8_t _byte2)
Register2 (char sign, uint8_t _byte1, uint8_t _byte2)
void reset ()
uint8_t operator[] (int index) const
uint16_t bytes12 () const
int16_t value () const
void set (int16_t value)
void set (int index, int8_t val)
void set (bool negative, uint8_t byte1, uint8_t byte2)
void set (char sign, uint8_t byte1, uint8_t byte2)
Public Attributes
bool negative
uint8_t byte1
uint8_t byte2
Detailed Description
The register with 2 bytes (rI, rJ).
The 2 bytes registers are used to represent locations and offsets. It contains a sign indicator (+ or -) and 2 bytes. Each byte can represent at least [0, 64) integers.
Definition at line 23 of file registers.h.
Constructor & Destructor Documentation
Register2() [1/4]
mixal::Register2::Register2 ()
Initialize the register with zeros.
Definition at line 7 of file registers.cpp.
                      : negative(), byte1(), byte2() {
 }
Register2() [2/4]
mixal::Register2::Register2 (int16_t value) explicit
Initialize the register with an integer value.
See also
set(int16_t)
Definition at line 10 of file registers.cpp.
                                   : negative(), byte1(), byte2() {
     set(value);
 }
References set(), and value().
Register2() [3/4]
mixal::Register2::Register2 (bool _negative, uint8_t _byte1, uint8_t _byte2)
Initialize the register with all the specific values.
Definition at line 14 of file registers.cpp.
                                                                    :
     negative(_negative), byte1(_byte1), byte2(_byte2) {
 }
Register2() [4/4]
mixal::Register2::Register2 (char sign, uint8_t _byte1, uint8_t _byte2)
Initialize the register with all the specific values.
Exceptions
std::runtime_error when the sign is neither '+' nor '-'.
Definition at line 18 of file registers.cpp.
                                                               :
     negative(sign == '-'), byte1(_byte1), byte2(_byte2) {
     if (sign != '+' && sign != '-') {
         throw std::runtime_error("Invalid sign: " + std::string(1, sign));
     }
 }
Member Function Documentation
bytes12()
uint16_t mixal::Register2::bytes12 () const
Get the absolution value of the register.
Definition at line 35 of file registers.cpp.
{
     int16_t high = static_cast<int16_t>(static_cast<uint8_t>(byte1));
     int16_t low = static_cast<int16_t>(static_cast<uint8_t>(byte2));
     return high * 64 + low;
 }
Referenced by value().
operator[]()
uint8_t mixal::Register2::operator[] (int index) const
Get the value with index in [1, 2].
Exceptions
std::runtime_error when the index is not in [1, 2].
Definition at line 25 of file registers.cpp.
{
     if (index == 1) {
         return byte1;
     }
     if (index == 2) {
         return byte2;
     }
     throw std::runtime_error("Invalid index for a two bytes register: " + std::to_string(index));
 }
reset()
void mixal::Register2::reset () inline
Reset the values in the register to 0.
Definition at line 44 of file registers.h.
{
         negative = false;
         byte1 = byte2 = 0;
     }
Referenced by mixal::Computer::reset().
set() [1/4]
void mixal::Register2::set (bool negative, uint8_t byte1, uint8_t byte2)
Set all the values.
Definition at line 67 of file registers.cpp.
{
     this->negative = negative;
     this->byte1 = byte1;
     this->byte2 = byte2;
 }
set() [2/4]
void mixal::Register2::set (char sign, uint8_t byte1, uint8_t byte2)
Set all the values.
Exceptions
std::runtime_error when the sign is neither '+' nor '-'.
Definition at line 73 of file registers.cpp.
{
     if (sign != '+' && sign != '-') {
         throw std::runtime_error("Invalid sign: " + std::string(1, sign));
     }
     this->negative = sign == '-';
     this->byte1 = byte1;
     this->byte2 = byte2;
 }
set() [3/4]
void mixal::Register2::set (int index, int8_t val)
Set specific byte with the given index in [1, 2].
Parameters
val The behavior is undefined if it is greater than 63.
Exceptions
std::runtime_error when the index is not in [1, 2].
Definition at line 57 of file registers.cpp.
{
     if (index == 1) {
         byte1 = val;
     } else if (index == 2) {
         byte2 = val;
     } else {
         throw std::runtime_error("Invalid index for a two bytes register: " + std::to_string(index));
     }
 }
set() [4/4]
void mixal::Register2::set (int16_t value)
Set the register with an integer.
The sign will be set only when the input is non-zero. Therefore to set the word to -0 with this function, one can set it with a negative value first, then set it to 0.
The least significant 12 bits will be saved to the word. Each byte contains 6 bits. The byte2 will contain the least significant 6 bits.
Definition at line 46 of file registers.cpp.
{
     if (value > 0) {
         negative = false;
     } else if (value < 0) {
         negative = true;
         value = -value;
     }
     byte1 = static_cast<uint8_t>(value / (1 << 6));
     byte2 = static_cast<uint8_t>(value % (1 << 6));
 }
References value().
Referenced by Register2().
value()
int16_t mixal::Register2::value () const
Get the value represented by the register.
Definition at line 41 of file registers.cpp.
{
     int16_t val = static_cast<int16_t>(bytes12());
     return negative ? -val : val;
 }
References bytes12().
Referenced by Register2(), and set().
The documentation for this struct was generated from the following files:
include/registers.h
src/registers.cpp