name: C++ Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: sync
      run: git submodule update --init --recursive
    - name: install/apt
      run: sudo apt install -y cmake lcov
    - name: install/pip
      run: python -m pip install --upgrade pip && python -m pip install cpplint
    - name: test
      run: ./test_cpp.sh
