name: Unit Tests

on: [push, pull_request]

jobs:
  cpp:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: sync
      run: git submodule update --init --recursive
    - name: install/apt
      run: sudo apt install -y cmake lcov
    - name: install/pip
      run: python -m pip install --upgrade pip && python -m pip install cpplint mixal
    - name: test
      run: ./test_cpp.sh
  python:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: sync
      run: git submodule update --init --recursive
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        if [ -f requirements-dev.txt ]; then pip install -r requirements-dev.txt; fi
    - name: Test
      run: ./test_py.sh
